// @vitest-environment jsdom
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import {
    beforeEach,
    expect,
    test,
    vi,
} from 'vitest';

import { getRulesFromEditor, initEditor, setEditorValue } from '../src/init-editor';
import { WasmLoadError } from '../src/lib/errors';
import { RegistryManager } from '../src/lib/registry';

const wasm = readFileSync(
    resolve(__dirname, '../node_modules/vscode-oniguruma/release/onig.wasm'),
).buffer;

beforeEach(() => RegistryManager.resetForTests());

test('mounts an editor and highlights a comment', async () => {
    const textarea = document.createElement('textarea');
    document.body.appendChild(textarea);
    const view = await initEditor(textarea, wasm, { hotkeys: { mode: 'mac' } });
    view.dispatch({ changes: { from: 0, insert: '! comment' } });
    // The comment is wrapped in a highlighted span (class generated by the
    // active HighlightStyle), confirming syntax highlighting is applied.
    const span = view.dom.querySelector('.cm-line span');
    expect(span).not.toBeNull();
    expect(span!.textContent).toBe('! comment');
    expect(span!.className).not.toBe('');
    view.destroy();
});

test('setEditorValue + getRulesFromEditor round-trips enabled flags', async () => {
    const textarea = document.createElement('textarea');
    document.body.appendChild(textarea);
    const view = await initEditor(textarea, wasm, { hotkeys: { mode: 'mac' }, withBreakpoints: true });
    setEditorValue(view, [
        { enabled: true, rule: '||a.com^' },
        { enabled: false, rule: '||b.com^' },
    ], {});
    const rules = getRulesFromEditor(view);
    expect(rules).toEqual([
        { enabled: true, rule: '||a.com^' },
        { enabled: false, rule: '||b.com^' },
    ]);
    view.destroy();
});

test("highlight: 'none' mounts without loading WASM", async () => {
    const spy = vi.spyOn(RegistryManager, 'getGrammar');
    const textarea = document.createElement('textarea');
    document.body.appendChild(textarea);
    const view = await initEditor(textarea, undefined, {
        hotkeys: { mode: 'mac' },
        highlight: 'none',
    });
    view.dispatch({ changes: { from: 0, insert: '! comment' } });
    expect(spy).not.toHaveBeenCalled();
    // No language extension -> no highlighted spans.
    expect(view.dom.querySelector('.cm-line span')).toBeNull();
    expect(view.dom.textContent).toContain('! comment');
    spy.mockRestore();
    view.destroy();
});

test("highlight: 'full' without a WASM source throws WasmLoadError", async () => {
    const textarea = document.createElement('textarea');
    document.body.appendChild(textarea);
    await expect(
        initEditor(textarea, undefined, { hotkeys: { mode: 'mac' }, highlight: 'full' }),
    ).rejects.toBeInstanceOf(WasmLoadError);
});

test('HighlightMode is exported from the package entry point', async () => {
    const mod = await import('../src/index');
    // Type-only export has no runtime value; assert the function is present
    // and a typed usage compiles (compilation is checked by `pnpm run build`).
    // eslint-disable-next-line @typescript-eslint/consistent-type-imports
    const value: import('../src/index').HighlightMode = 'none';
    expect(mod.initEditor).toBeTypeOf('function');
    expect(value).toBe('none');
});
