// @vitest-environment jsdom
import { test, expect, beforeEach } from 'vitest';
import { readFileSync } from 'fs';
import { resolve } from 'path';
import { initEditor, getRulesFromEditor, setEditorValue } from '../src/initEditor';
import { resetRegistryForTests } from '../src/lib/registry';

const wasm = readFileSync(
    resolve(__dirname, '../node_modules/vscode-oniguruma/release/onig.wasm'),
).buffer;

beforeEach(() => resetRegistryForTests());

test('mounts an editor and highlights a comment', async () => {
    const textarea = document.createElement('textarea');
    document.body.appendChild(textarea);
    const view = await initEditor(textarea, wasm, { hotkeys: { mode: 'mac' } });
    view.dispatch({ changes: { from: 0, insert: '! comment' } });
    // The comment is wrapped in a highlighted span (class generated by the
    // active HighlightStyle), confirming syntax highlighting is applied.
    const span = view.dom.querySelector('.cm-line span');
    expect(span).not.toBeNull();
    expect(span!.textContent).toBe('! comment');
    expect(span!.className).not.toBe('');
    view.destroy();
});

test('setEditorValue + getRulesFromEditor round-trips enabled flags', async () => {
    const textarea = document.createElement('textarea');
    document.body.appendChild(textarea);
    const view = await initEditor(textarea, wasm, { hotkeys: { mode: 'mac' }, withBreakpoints: true });
    setEditorValue(view, [
        { enabled: true, rule: '||a.com^' },
        { enabled: false, rule: '||b.com^' },
    ], {});
    const rules = getRulesFromEditor(view);
    expect(rules).toEqual([
        { enabled: true, rule: '||a.com^' },
        { enabled: false, rule: '||b.com^' },
    ]);
    view.destroy();
});
