// @vitest-environment jsdom
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { undo } from '@codemirror/commands';
import { searchPanelOpen } from '@codemirror/search';
import { type EditorView } from '@codemirror/view';
import {
    beforeEach,
    expect,
    test,
    vi,
} from 'vitest';

import { getRulesFromEditor, initEditor, setEditorValue } from '../src/init-editor';
import { WasmLoadError } from '../src/lib/errors';
import { RegistryManager } from '../src/lib/registry';

const wasm = readFileSync(
    resolve(__dirname, '../node_modules/vscode-oniguruma/release/onig.wasm'),
).buffer;

beforeEach(() => RegistryManager.resetForTests());

/**
 * Dispatches a Ctrl+<key> keydown event on the editor's content DOM.
 *
 * @param view The editor view to dispatch the event on.
 * @param key The letter pressed with Ctrl held down.
 *
 * @returns The dispatched event.
 */
const pressCtrlKey = (view: EditorView, key: string): KeyboardEvent => {
    const event = new KeyboardEvent('keydown', {
        key,
        ctrlKey: true,
        bubbles: true,
        cancelable: true,
    });
    view.contentDOM.dispatchEvent(event);
    return event;
};

test('mounts an editor and highlights a comment', async () => {
    const textarea = document.createElement('textarea');
    document.body.appendChild(textarea);
    const view = await initEditor(textarea, wasm, { hotkeys: { mode: 'mac' } });
    view.dispatch({ changes: { from: 0, insert: '! comment' } });
    // The comment is wrapped in a highlighted span (class generated by the
    // active HighlightStyle), confirming syntax highlighting is applied.
    const span = view.dom.querySelector('.cm-line span');
    expect(span).not.toBeNull();
    expect(span!.textContent).toBe('! comment');
    expect(span!.className).not.toBe('');
    view.destroy();
});

test('setEditorValue + getRulesFromEditor round-trips enabled flags', async () => {
    const textarea = document.createElement('textarea');
    document.body.appendChild(textarea);
    const view = await initEditor(textarea, wasm, { hotkeys: { mode: 'mac' }, withBreakpoints: true });
    setEditorValue(view, [
        { enabled: true, rule: '||a.com^' },
        { enabled: false, rule: '||b.com^' },
    ], {});
    const rules = getRulesFromEditor(view);
    expect(rules).toEqual([
        { enabled: true, rule: '||a.com^' },
        { enabled: false, rule: '||b.com^' },
    ]);
    view.destroy();
});

test("highlight: 'none' mounts without loading WASM", async () => {
    const spy = vi.spyOn(RegistryManager, 'getGrammar');
    const textarea = document.createElement('textarea');
    document.body.appendChild(textarea);
    const view = await initEditor(textarea, undefined, {
        hotkeys: { mode: 'mac' },
        highlight: 'none',
    });
    view.dispatch({ changes: { from: 0, insert: '! comment' } });
    expect(spy).not.toHaveBeenCalled();
    // No language extension -> no highlighted spans.
    expect(view.dom.querySelector('.cm-line span')).toBeNull();
    expect(view.dom.textContent).toContain('! comment');
    spy.mockRestore();
    view.destroy();
});

test("highlight: 'full' without a WASM source throws WasmLoadError", async () => {
    const textarea = document.createElement('textarea');
    document.body.appendChild(textarea);
    await expect(
        initEditor(textarea, undefined, { hotkeys: { mode: 'mac' }, highlight: 'full' }),
    ).rejects.toBeInstanceOf(WasmLoadError);
});

test('HighlightMode is exported from the package entry point', async () => {
    const mod = await import('../src/index');
    // Type-only export has no runtime value; assert the function is present
    // and a typed usage compiles (compilation is checked by `pnpm run build`).
    // eslint-disable-next-line @typescript-eslint/consistent-type-imports
    const value: import('../src/index').HighlightMode = 'none';
    expect(mod.initEditor).toBeTypeOf('function');
    expect(value).toBe('none');
});

test('Ctrl+Shift+Z redoes the last undone change', async () => {
    const textarea = document.createElement('textarea');
    document.body.appendChild(textarea);
    const view = await initEditor(textarea, undefined, {
        hotkeys: { mode: 'windows' },
        highlight: 'none',
    });

    view.dispatch({ changes: { from: 0, insert: '||example.com^' } });
    expect(undo(view)).toBe(true);
    expect(view.state.doc.toString()).toBe('');

    // Simulate Ctrl+Shift+Z. jsdom's `navigator.platform` is empty, so
    // CM6 resolves keymaps on its generic "key" platform, where `Mod`
    // means Ctrl — reproducing the Windows binding set (the
    // `hotkeys.mode` config does not affect keymap resolution). Real
    // browsers report `key` as uppercase 'Z' while Shift is held; CM6
    // then resolves the binding through `base[event.keyCode]`. jsdom
    // never populates the legacy `keyCode`, so stub it (90 = Z).
    const event = new KeyboardEvent('keydown', {
        key: 'Z',
        ctrlKey: true,
        shiftKey: true,
        bubbles: true,
        cancelable: true,
    });
    Object.defineProperty(event, 'keyCode', { get: () => 90 });
    view.contentDOM.dispatchEvent(event);

    expect(event.defaultPrevented).toBe(true);
    expect(view.state.doc.toString()).toBe('||example.com^');
    view.destroy();
});

test('focuses the editor on initialization so hotkeys work immediately', async () => {
    const textarea = document.createElement('textarea');
    document.body.appendChild(textarea);
    const view = await initEditor(textarea, undefined, {
        hotkeys: { mode: 'windows' },
        highlight: 'none',
    });
    // AG-58146: the editor must be focused as soon as it is created,
    // otherwise CodeMirror keymaps (Ctrl+F/Ctrl+H) ignore keydown events
    // until the user clicks inside the editor.
    expect(view.hasFocus).toBe(true);
    expect(document.activeElement).toBe(view.contentDOM);
    view.destroy();
});

test('does not steal focus when autofocus is disabled', async () => {
    const textarea = document.createElement('textarea');
    document.body.appendChild(textarea);
    const input = document.createElement('input');
    document.body.appendChild(input);
    input.focus();

    const view = await initEditor(textarea, undefined, {
        hotkeys: { mode: 'windows' },
        highlight: 'none',
        // AG-58146: pages with several editors (or a focused element
        // elsewhere) opt out so the editor does not steal focus on creation.
        autofocus: false,
    });

    expect(view.hasFocus).toBe(false);
    expect(document.activeElement).toBe(input);
    view.destroy();
});

test('Ctrl+F opens the search panel at the bottom of the editor', async () => {
    const textarea = document.createElement('textarea');
    document.body.appendChild(textarea);
    const view = await initEditor(textarea, undefined, {
        hotkeys: { mode: 'windows' },
        highlight: 'none',
    });

    const event = pressCtrlKey(view, 'f');

    expect(event.defaultPrevented).toBe(true);
    expect(searchPanelOpen(view.state)).toBe(true);
    expect(view.dom.querySelector('.cm-panel.cm-search')).not.toBeNull();
    // AG-58146: the default search UI is pinned to the bottom of the editor.
    expect(view.dom.querySelector('.cm-panels-bottom')).not.toBeNull();
    expect(view.dom.querySelector('.cm-panels-top')).toBeNull();
    view.destroy();
});

test('Ctrl+H opens the search panel with the focus in the replace field', async () => {
    const textarea = document.createElement('textarea');
    document.body.appendChild(textarea);
    const view = await initEditor(textarea, undefined, {
        hotkeys: { mode: 'windows' },
        highlight: 'none',
    });

    const event = pressCtrlKey(view, 'h');

    expect(event.defaultPrevented).toBe(true);
    expect(searchPanelOpen(view.state)).toBe(true);
    const replaceField = view.dom.querySelector<HTMLInputElement>(
        '.cm-panel.cm-search input[name="replace"]',
    );
    expect(replaceField).not.toBeNull();
    // AG-58146: Ctrl+H is "find & replace", so the replace field must get the
    // focus (unlike Ctrl+F which focuses the find field).
    expect(document.activeElement).toBe(replaceField);
    view.destroy();
});
